### ISSUE TITLE
MVP

### ISSUE THREAD

**Issue by ArsenGadjiusmanov** [gamabuntat/super-slider#1]
Архитектура проекта по заданию должна MVP. Почему у тебя Model называется Service. Хотя внутри Service ты вызываешь методы с model

**Comment by gamabuntat** [comment]
Да, это одна из реализаций MVP (как я понял). Service нужен для централизованного взаимодействия с моделями и для "общения с внешним миром". Service хранит в себе модели и поэтому названия его методов содержат 'model'. Мне бы все равно пришлось реализовывать функции сервиса где-то в другом месте. Мне показалось это интересным( И источником данных для модели может быть все что угодно, например localStorage. Кароче получается такой единый интерфейс для манипуляций с моделями.

**Comment by ArsenGadjiusmanov** [comment]
> Да, это одна из реализаций MVP (как я понял). Service нужен для централизованного взаимодействия с моделями и для "общения с внешним миром". Service хранит в себе модели и поэтому названия его методов содержат 'model'. Мне бы все равно пришлось реализовывать функции сервиса где-то в другом месте. Мне показалось это интересным( И источником данных для модели может быть все что угодно, например localStorage. Кароче получается такой единый интерфейс для манипуляций с моделями.
