### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by Feinminen** [gamabuntat/super-slider#11]
Надо поправить тесты, они начали фейлится 
![image](https://user-images.githubusercontent.com/44312820/149657516-2ee287b0-91ac-4280-ba8c-85133fcb6629.png)

**Comment by gamabuntat** [comment]
у меня тесты номр запускаются
![2022-01-16-192111_912x732_scrot](https://user-images.githubusercontent.com/55852712/149657997-eb04a936-ab16-4d24-914f-d81c13ddae52.png)

**Comment by gamabuntat** [comment]
> Надо поправить тесты, они начали фейлится ![image](https://user-images.githubusercontent.com/44312820/149657516-2ee287b0-91ac-4280-ba8c-85133fcb6629.png)

У меня они норм запускаются
![2022-01-16-192111_912x732_scrot](https://user-images.githubusercontent.com/55852712/149658022-21d61bdf-8b78-4502-8b0d-547ba1d27038.png)

**Comment by Feinminen** [comment]
Мхм, окей, у меня просто до правок нормально работали, после поломались. Хотя все модули я переинстолил
