### ISSUE TITLE
Class constructors

### ISSUE THREAD

**Issue by Feinminen** [gamabuntat/super-slider#13]
Также не всегда выполняется [ЭТОТ](https://github.com/fullstack-development/front-end-best-practices/blob/f4139eb680dacb7b35040d0f0b0a2edb6372eb8e/JS/README.md#1.12) пункт стандартов. (в View.ts констуркторе, например)

**Comment by gamabuntat** [comment]
> Также не всегда выполняется [ЭТОТ](https://github.com/fullstack-development/front-end-best-practices/blob/f4139eb680dacb7b35040d0f0b0a2edb6372eb8e/JS/README.md#1.12) пункт стандартов. (в View.ts констуркторе, например)

ну а как эту легковестность измерить? относительно класса в 300 почти строк у View достаточно минималистичный конструктор. в нем нету поиска по дом и он не вешает никаких обработчиков. Мне просто сделать вызов из конструктора вию метода инит, и тогда все хорошо будет? Мне кажется, что конструктор, в данном случае, не делает ничего лишнего, в нем просто создается инстанс класса
