### ISSUE TITLE
MVP

### ISSUE THREAD

**Issue by Feinminen** [gamabuntat/super-slider#14]
В требованиях описано, что на выходе должна получиться MPV архитектура с пассивной вьюхой. Вьюха вообще ни коим образом не должна знать о Модели, а все взаимодействия между вью и моделью должны быть выполнены через контроллер с ивент эмиттером.
У тебя вью принимает модель из-за чего можно спокойно обратиться к любому свойству или методу модели напрямую, что нарушает инкапсуляцию и увеличивает сцепление слоев.

**Comment by gamabuntat** [comment]
> В требованиях описано, что на выходе должна получиться MPV архитектура с пассивной вьюхой. Вьюха вообще ни коим образом не должна знать о Модели, а все взаимодействия между вью и моделью должны быть выполнены через контроллер с ивент эмиттером. У тебя вью принимает модель из-за чего можно спокойно обратиться к любому свойству или методу модели напрямую, что нарушает инкапсуляцию и увеличивает сцепление слоев.

Она же принимает не класс, а просто копию объекта с опциями, после того когда состояние слайдера меняется посредтвом взаимодействия с UI, она как раз и вызывает метод ивен эммитора с обновленными опциями

**Comment by Feinminen** [comment]
Обсудили как лучше сделать в ЛС, теперь всё ок :)
