### ISSUE TITLE
Тесты

### ISSUE THREAD

**Issue by ArsenGadjiusmanov** [gamabuntat/super-slider#5]
Какие-то тесты не проходят проверку посмотри пожалуйста
![image](https://user-images.githubusercontent.com/89850975/136124775-efd2be21-e00c-4232-9db1-c15a937bac36.png)

**Comment by ArsenGadjiusmanov** [comment]
![image](https://user-images.githubusercontent.com/89850975/136658224-2b4ae73c-2e7e-4e7c-9b6e-aef5a975601e.png)
Что-то ты сломал. Теперь они вовсе не работают. Добавь в зависимости jest

Все тесты должны успешно завершаться. Покрытие должно быть не меньше ~80%

**Comment by ArsenGadjiusmanov** [comment]
Возможно у тебя какие-то пакеты глобально установлены. В package.json должны быть прописаны все необходимые зависимости

**Comment by ArsenGadjiusmanov** [comment]
https://media.discordapp.net/attachments/415935995825881108/896497633315668008/unknown.png
Код на другом компе так же

**Comment by gamabuntat** [comment]
![hihe](https://user-images.githubusercontent.com/55852712/136673841-85714507-eb53-4974-adce-d8ac65e12305.png)

блин, интересно

**Comment by gamabuntat** [comment]
а что вы делать предлагаете? может вы мне логи скините и ошибку, когда запускаете через `npx jest`?

**Comment by ArsenGadjiusmanov** [comment]
![image](https://user-images.githubusercontent.com/89850975/137120039-355974d1-ddc4-437a-9ff9-da6a2a1836a1.png)
надо поднять до 80% все

**Comment by ArsenGadjiusmanov** [comment]
> > ![image](https://user-images.githubusercontent.com/89850975/137120039-355974d1-ddc4-437a-9ff9-da6a2a1836a1.png) надо поднять до 80% все
> 
> оо у вас запустилось?

Да)

**Comment by gamabuntat** [comment]
> Да)
а что было?

> Сможешь сегодня исправить?
да

**Comment by ArsenGadjiusmanov** [comment]
> > Да)
> > а что было?
> 
> > Сможешь сегодня исправить?
> > да

Версия node

**Comment by gamabuntat** [comment]
а вот где branch 60 - 70% не пойдет?

**Comment by ArsenGadjiusmanov** [comment]
> а вот где branch 60 - 70% не пойдет?

Желательно чтобы все было зеленым, если есть возможность сделай)
