### ISSUE TITLE
BEM

### ISSUE THREAD

**Issue by Feinminen** [gamabuntat/super-slider#9]
Сейчас в проекте не соблюдаются многие BEM правила, этот проект тоже должен соответствовать всем BEM-у :)
И многие стилистические элементы отличаются от первого проекта, например для модификаторов тут используется double dash вместо underscore.

**Comment by Feinminen** [comment]
Подскажи, а нельзя привести Slider.module.sass к более "БЭМному" виду. Просто сейчас это выглядит как куча разрозненных компонентов.
Я просто никогда не юзал scss модули, поэтому не могу точно сказать что лучше сделать :)

**Comment by gamabuntat** [comment]
я юзал на командном этапе, нам тех лид там говорил делать)

> Подскажи, а нельзя привести Slider.module.sass к более "БЭМному" виду. Просто сейчас это выглядит как куча разрозненных компонентов. Я просто никогда не юзал scss модули, поэтому не могу точно сказать что лучше сделать :)

я юзал на командном этапе, нам тех лид там говорил делать)

**Comment by Feinminen** [comment]
окей, просто выглядит крайне непривычно. Тогда закрываю ишью
